// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aibgalkljrgnpepcnwgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpYmdhbGtsanJnbnBlcGNud2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTM0OTksImV4cCI6MjA2NTgyOTQ5OX0.X5YDMBOMd2mKjV2JOPYi_i1n0GqDr-r23oiFdsv2c_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);